### PR TITLE
feat(Shorthand): Children API / Shorthand API new toggle experience and css improvements

### PR DESCRIPTION
**Pull request by bmdalex**
**Description** feat(Shorthand):
- enforcing addition of shorthand examples
- adding new UI for toggling between Shorthand API and Children API
- improved styling of examples

**Links to DEMO**:
- [Video](http://recordit.co/WfAO2mrjbx)
- [GIF](http://g.recordit.co/WfAO2mrjbx.gif)

fyi @levithomason

### CODE REVIEW

**Comment by mnajdova** [comment]
This looks great! One thing that I think can be changed is, when there is not shorthand example and we click the edit code maybe we should just show the Children API code, because we know that we don't have anything to show for the Shorthand API. @Bugaa92 what do you think?

**Comment by bmdalex** [comment]
@mnajdova 
yup, that's a great point. I actually had that implemented, but the reasons I didn't go with it are the following:
- it might be unclear for the dev what `.shorthand` version (corresponding to which example?) is not implemented unless he navigates to the shorthand tab to see that
- the current way (showing the `missing shorthand example placeholder`) would encourage devs to actually add the `.shorthand` example when they see it missing; ideally, the regular user will never see the `missing shorthand example placeholder` as all component will have it implemented, so this is more like a way of educating the devs to write all required examples

An argument in your favor is that there is already a generic `missing shorthand example placeholder` at the beginning of the examples section which might be enough to educate the devs to introduce these missing examples (see example below)

screen shot 2018-07-10 at 12 17 25

which means we could implement your suggestion.
@levithomason what do you think?

**Comment by bmdalex** [comment]
@levithomason - Just implemented @mnajdova 's suggestion and added the disabled property to the `Children API` button when example is not provided.
@miroslavstastny can you also take a look at the files related to the menu examples? I had a conflict there

**Comment by mnajdova** [comment]
The only change that I see regarding the Menu component is adding title and content to all examples and removing the Shorthand example. I run it locally and it looks ok. If this is the only file that contained conflicts, then everything regarding the Menu component should be ok.

**Comment by mnajdova** [comment]
Looks good to be merged here. I like how each combination of shorthand or regular example missing is shown.

**Review by mnajdova — APPROVED** [review]

**Pull request merged**
