### PR TITLE
Add generator for component files

### PR DESCRIPTION
**Pull request by kuzhelov**
Initial version of generator is added. This should help to 
- scaffold basic files to provide basic content for component
- export component from lib 
- consume it on the docs side. 

Basic checks are introduced as well - with the main goal of preventing overrides for existing files, as well as enforcing naming convention.

The following command launches generation process: `yarn generate`.

**Would very appreciate any suggestions in regards to where this functionality should reside** in project's file hierarchy (currently it resides in a single file, but, ideally, should be split), **as well as any suggestions in terms of better naming that we should adhere to**. Thank you :)

### CODE REVIEW

**Comment by mnajdova** [comment]
Maybe it would be a good idea the generate command to create the test for the component as well? The structure for the tests is the same as the components and the naming convention so far is _ComponentName-test.ts_. In the test we could provide the isConformance test by default.

**Comment by kuzhelov** [comment]
yes, sure, we should consider that - however, am rather inclined to address this problem as a separate PR, and see this one as a remedy for developer to be able to quickly set up docs as a dev environment for new component :) @mnajdova, what do you think?

**Comment by mnajdova** [comment]
Sure, make sense... :)

**Comment by levithomason** [comment]
What about keeping a directory of template files and replacing their contents?  This would make reviewing and changing the templates very simple.

We could also very easily copy the files, update their contents and place them in a destination directory using the existing gulp infrastructure.  This would remove the need for the touch, ensureDir, and createFileTree functions since gulp does this automatically. Pseudo example:

```jsx
// TemplateComponent.tsx

const $COMPONENT = () => <$ELEMENT />
```

```jsx
// gulp/tasks/generate.ts

task('generate:component', () => {
  const { name, element } = require('yargs').argv

  return src('./TemplateComponent.tsx')
    .pipe(g.replace('$COMPONENT', name)
    .pipe(g.replace('$ELEMENT', element)
    .pipe(g.rename({ basename: `${name}.tsx` }))
    .pipe(dest(paths.src('components'))
})
```

```jsx
// package.json
{
  scripts: {
    "generate:component": "gulp generate:component"
  }
}
```

Then we can use it with command line args like so:

```bash
$ yarn generate:component Button
```

This could also be easily extended to take a type and name, etc:
```bash
$ yarn generate <type> <name>
```

**Comment by kuzhelov** [comment]
@levithomason, I've reworked changes with the approach you've suggested - please, take another look. Thanks :)

**Comment by levithomason** [comment]
This looks good for now.  Merging to try an catch up on PRs 👍

**Pull request merged**
