### PR TITLE
Test/is conformant

### PR DESCRIPTION
**Pull request by mnajdova**
Changed isConformant test to use jest and work with the latest changes of the createComponent helper
Showcased different approaches for providing custom messages for the except statements when using jest:
- using try-catch blocks - simple, but doesn't provide info about the actual difference between the expected and received values
- using object in the expect statements, where one of the prop is the message we want to provide (useful for showing the message and the difference between the actual and expected values, but it makes the expect statements harder to read)

### CODE REVIEW

**Comment by levithomason** [comment]
I get a failure on `Image-test.js`.  Is this PR ready for review?

```
 FAIL  test/specs/components/Image/Image-test.js
  ● Image › className (common) › applies user's className to root component

    expect(received).toEqual(expected)

    Expected value to equal:
      true
    Received:
      false
```

**Comment by levithomason** [comment]
I have also merged master and fixed the conflicts.  The same error as above is still present.

**Comment by mnajdova** [comment]
It should fail, the user's classNames are not applied to the root component.
screenshot_27

**Comment by levithomason** [comment]
I see, let's update the components to pass as part of this PR.

**Comment by mnajdova** [comment]
It's fixed now.

**Pull request merged**
